Feat/dev design system
ate-eight/sell-your-unhappiness-front pull request #12
Opened 2024-02-07 00:47 UTC by heywon0909

## 📖 관련 문서
-  storybook UI 작업
  1. header Component
  2. Tab Component

- 글꼴 error 해결 
  1. preview-head.html 
    - web 에서 가져오는 font가 아니므로 link preload 태그 
       제거
    - src > assets > fonts 폴더 에 font 다운
  2. 전역 사용 가능하도록 font.css 파일 생성
## ✍🏻 변경사항:  
1. storybook Header / Tab Component 생성
2. .storybook preview-head.html 수정
3. src>assets>fonts 폴더 생성 및 font.css 생성 

ex) 중요 커밋은 링크로 연결해서 추가

## 🔍 확인할 목록

1. storybook UI 컴포넌트 정상 동작 확인
2. font 적용 되었는지 확인 필요 
3. header 중복 해결

2024-02-07 10:31 UTC, bbung95 approved these changes
고생하셨습니다!! 머지하시죠!

2024-02-08 16:09 UTC, mingnana commented
고생하셨습니다~!

2024-02-08 17:48 UTC, bbung95 approved these changes
고생하셨습니다!! 머지하시죠!

2024-02-08 17:48 UTC, bbung95 commented on src/components/navigation/Nav.tsx
> +    onUrl: () => void;
홈에서 목록 View Type 변경하는 이벤트로 알고 있는데 라우터 변경인지 Style 변경인지 정해지지 않은거 같아요!
큰건 아닌데 구현하시는 방향에 맞춰 name이 변경될 수 있을거 같아요!

2024-02-12 08:29 UTC, bbung95 requested changes

2024-02-12 08:29 UTC, bbung95 commented on src/components/text/style.ts
혜원님 이제 봤네요ㅠㅠ
const H4_ENG = styled.h3<{ color?: string }> 부분이 h4가 아니라 h3로 되어 있습니다!!

2024-02-14 00:46 UTC, heywon0909 commented on src/components/text/style.ts
앗 ㅠㅠㅠ 넵넵! 스타일 수정 완료하였습니다!

2024-02-14 00:46 UTC, heywon0909 commented on src/components/navigation/Nav.tsx
> +    onUrl: () => void;
넵넵! 그렇게 하시죠!

2024-02-14 06:20 UTC, bbung95 commented on src/stories/Colors.mdx
> +            key={item}
key가 빠져 있었군요..!! key에 참조형보다는 원시타입으로 item[0]을 넣는게 좋을거 같습니다!

2024-02-14 06:40 UTC, bbung95 approved these changes

2024-02-14 06:56 UTC, merged