글 상세 페이지 API 연동
ate-eight/sell-your-unhappiness-front pull request #35
Opened 2024-03-05 05:01 UTC by mingnana

## 📖 관련 문서
#34 

## ✍🏻 변경사항:
![image](https://github.com/ate-eight/sell-your-unhappiness-front/assets/96216178/e5563f2d-bf04-4605-89ce-0d3cd9e1e1f3)

1. Router.tsx 코드 리팩토링
- content 부분 중첩라우팅 설정했습니다.

2.  게시글 API 연동
- 성은님이 만드신 fetch 모듈 사용해서 작업했고, try-catch문 사용해서 에러처리해두었습니다. 
- api 데이터 적용 후 깨진 style을 수정했습니다.
- 글 영역과 댓글 영역의 기반이 되는 detail.tsx 파일에서 통신 후 각각 필요한 인자값을 props로 넘겨주는 방식으로 구현했는데, 혹시 다른 방법이 있다면 알려주세요 !!

3.  댓글 API 연동
- 게시글과 마찬가지로 fetch 모듈 사용해서 작업했고, try-catch문 사용해서 에러처리해두었습니다.
- comment와 관련된 파일을 contents/detail -> contents/comment 폴더로 이동했습니다.

- try-catch문 외부에 null 값 추가하였습니다. return null을 제외시키니 해당 함수를 사용하는 곳에서 
[ 'undefined' 형식은 'SetStateAction<ICommentResponse | null>' 형식에 할당할 수 없습니다.] 라고 에러가 뜨더라구요.. ㅜㅜ 구글링해보니 함수의 반환 유형을 명시적으로 지정해야한다고 해서 return을 추가했는데 문제있다면 알려주세요 !!

## 🔍 확인할 목록
- 1번 게시글 API 정상 동작 => http://localhost:3000/contents/1
- 1번 게시글 댓글 정상 동작

2024-03-06 06:10 UTC, heywon0909 commented on src/api/comment.ts
> +export const getComment = async (id: number) => {
```js
export const getComment: (id: number) => void = async (id: number) => {
    try {
        const response = await fetchData.get<ICommentResponse>(`/v1/board-comments?boardId=${id}`);
        const { data } = response.data;

        if (response.status === 200) {
            return data;
        }
    } catch (error) {
        console.error('Error occurred while fetching content detail:', error);
    }
    return;
};
이런식으로 하면 될 거 같습니다!
```

2024-03-06 06:11 UTC, heywon0909 commented on src/api/comment.ts
> +export interface ICommentResponse {
댓글 get  API 호출 후 받아오는 데이터를 보니 map property는 없는거 같은데 이 부분 어떤 부분인지 설명해 주실 수 있을까요??

2024-03-06 06:12 UTC, heywon0909 commented on src/api/contents.ts
> +export const getContentDetail = async (id: number) => {
여기도 동일하게 type 맞춰주시면 될 거 같습니다!

2024-03-06 06:14 UTC, heywon0909 commented on src/router/Router.tsx
> +                            <Route path='create' element={<CreatePage />} />
오오오오 좋습니다 👍👍👍

2024-03-06 06:15 UTC, heywon0909 commented on src/components/features/contents/style.ts
> +    }
좋습니다 👍👍👍

2024-03-06 06:17 UTC, heywon0909 commented on src/components/features/contents/detail/titleContainer.tsx
> +const TitleContainer = ({ contentsData }: IContentProps) => {
이 부분 contentsData  TitleContainer 내부에서 구조분해 할당해서 써주시면 될 거 같습니다!
- README문서 > 컴포넌트 Props 정의 
```js
const Components = ({title, color, size} : Props) => {
    //...
}

const Components = (props : Props) => {
	  const {title, color, size, fullWidth} = props;
    //...
}
```

2024-03-06 06:22 UTC, heywon0909 commented on src/components/features/contents/detail/detail.tsx
> +
혹시 이부분 useState 의 state type을 type | null  대신에 
```js
useState<type>(); 
```
이렇게 쓰는 거는 어떨까요? 후에 setState로 값을 셋팅할때 undefined 이 아니라면 setState를 호출할 수 있게끔 하면 조금 더 type이 깔끔해질 거 같습니다! 
이 부분은 선택의 문제라... 어떻게 생각하시나요?

2024-03-06 06:23 UTC, heywon0909 commented on src/components/features/contents/comment/commentTheme.tsx
> +    const formattedCreateTime = new Date(commentData.createTime).toISOString().split('T')[0];
이 부분 contentsData TitleContainer 내부에서 구조분해 할당해서 써주시면 될 거 같습니다!

README문서 > 컴포넌트 Props 정의
```js
const Components = ({title, color, size} : Props) => {
    //...
}

const Components = (props : Props) => {
	  const {title, color, size, fullWidth} = props;
    //...
}
```

2024-03-06 06:24 UTC, heywon0909 reviewed
코멘트 달아놓았습니다~~ 확인부탁드립니당

2024-03-06 06:49 UTC, mingnana commented
> 코멘트 달아놓았습니다~~ 확인부탁드립니당

오오 감사해요! 확인해보겠습니다!!

2024-03-06 06:51 UTC, mingnana commented on src/api/comment.ts
> +export interface ICommentResponse {
댓글부분에서 map을 돌렸더니 에러가 나길래 추가했었는데 .. 다시 실행해보니 정상실행되네요..? ㅎㅎ map 속성은 삭제했습니다!

2024-03-06 07:22 UTC, mingnana commented on src/components/features/contents/detail/detail.tsx
> +
혜원님 방식도 좋은것같은데요 !! if문으로 undefined 처리하는 방식으로 수정하겠습니다~!

2024-03-06 07:49 UTC, mingnana commented on src/api/comment.ts
> +export const getComment = async (id: number) => {
export const getContentDetail: (id: number) => void = async (id: number) => {
    try {
        const response = await fetchData.get<IContentResponse>(`/v1/board-comments?boardId=${id}`);
        const { data } = response.data;
        if (response.status === 200) {
            return data;
        }
    } catch (error) {
        console.error('Error occurred while fetching content detail:', error);
    }
    return;
};

2024-03-06 07:50 UTC, mingnana commented
> 코멘트 달아놓았습니다~~ 확인부탁드립니당

수정했습니다 ~! 확인 부탁드릴게요 !!👍👍

2024-03-07 05:55 UTC, bbung95 requested changes
추가로 작업하신 내용 코멘트 달았습니다! 확인 부탁드릴게요!

2024-03-07 05:55 UTC, bbung95 commented on src/components/features/contents/detail/detail.tsx
> +    useEffect(() => {
<img width="623" alt="스크린샷 2024-03-05 오후 5 07 11" src="https://github.com/ate-eight/sell-your-unhappiness-front/assets/77668478/3fc56a7f-b009-444d-8931-f6cd74a33161">

https://careerly.co.kr/qnas/6469

fetch 부분을 react-query로 변경해봐도 좋을거 같아요!

2024-03-07 05:55 UTC, bbung95 commented on src/components/features/contents/detail/detail.tsx
> +    if (!contentsData || !commentData) {
null을 리턴하기보다 react-query와 Suspense를 사용해서 대체 컴포넌트를 보여줘도 좋을거 같습니다!

2024-03-07 05:55 UTC, bbung95 commented on src/router/Router.tsx
> +                        <Route path='contents'>
좋습니다! 👍

2024-03-07 05:55 UTC, bbung95 commented on src/api/contents.ts
> +export const getContentDetail: (id: number) => void = async (id: number) => {
```javascript
(id : number) => void
```

이 부분은 타입을 중복으로 선언하는거 같아요! 이미 param 타입 선언하고 리턴타입은 타입 추론으로 해결되는거 같아요!

그리고 리턴타입이 명시적으로 작성되서 void로 리턴한다고 인식이 된거같습니다

<img width="642" alt="스크린샷 2024-03-07 오후 2 38 32" src="https://github.com/ate-eight/sell-your-unhappiness-front/assets/77668478/10466d16-db4d-42b2-b1af-3aacb181f138">

detail.tsx 부분에 보면 리턴이 없다고 되어 있습니다!
저 부분은 삭제해도 무방할거 같아요

2024-03-07 05:55 UTC, bbung95 commented on src/components/features/contents/comment/commentContainer.tsx
> +                <S.CommentArea key={idx}>
key prop으로 인덱스 사용보다 id와 같은 고유값을 사용하는게 좋은거 같아요!

리엑트는 각 요소에 고유한 키 값을 넣어서 이전것과 변경을 비교하는 걸로 알고 있는데 index를 key로 사용했을 시에 변경이 있을 시 이전과 다른 key를 가지게 되어 문제가 발생할 수 있다고 합니다!

response에 id가 포함되어 있는거 같은데 id로 변경하면 좋을거 같습니다!

2024-03-07 05:55 UTC, bbung95 commented on src/components/features/contents/comment/commentTheme.tsx
> +const Comment = ({ commentsData: { id, content, createTime } }: ICommentProps) => {
뎁스가 있는 경우에는 Readme에 있는 2번째 방법으로 하면 좋을거 같아요!
prop이 추가됨에 따라 가독성에 안좋을거 같아요!

```javascript
const Components = ({ commentsData }: Props) => {
	  const {id, content, createTime} = commentsData;
    //...
}
```

2024-03-08 05:30 UTC, mingnana commented on src/components/features/contents/comment/commentContainer.tsx
> +                <S.CommentArea key={idx}>
앗 이부분 저도 들었던것같아요!! 수정했습니다~ 감사해요 !!

2024-03-08 09:38 UTC, mingnana commented on src/components/features/contents/detail/detail.tsx
> +    if (!contentsData || !commentData) {
null 부분은 제거하고 && 연산자로 처리했습니다!
만약 데이터가 없으면 페이지 자체가 리다이렉트가 되는게 맞을것같은데.. 기획이나 디자인적으로 고민해 봐야할것같아서 우선 보류했습니다! 
혹시 성은님 의견 여쭤봐도 될까요 !!

2024-03-08 09:39 UTC, mingnana commented on src/components/features/contents/detail/detail.tsx
> +    useEffect(() => {
추가했습니다! react-query가 처음이라 코드가 좀 미흡할것같은데.. 만약 피드백 주시면 바로 수정해놓을게요 ~ !

2024-03-08 10:14 UTC, bbung95 commented on src/components/features/contents/detail/detail.tsx
> +    if (!contentsData || !commentData) {
전 플로우가 fetch 데이터가 없을 경우에 아무것도 렌더링이 되지 않았어서 대체 컴포넌트를 생각했었습니다! (스켈레톤, 로딩...)

저는 리다이렉트로 바로 보내는것은 해당 URL이 존재하지 않을 경우에 이동하면 좋을거 같아요!

<img width="774" alt="스크린샷 2024-03-08 오후 7 08 16" src="https://github.com/ate-eight/sell-your-unhappiness-front/assets/77668478/3900fc45-a113-440f-9777-b743f8a4bd61">

2024-03-08 10:22 UTC, bbung95 commented on src/App.tsx
> +const queryClient = new QueryClient();
https://jong6598.tistory.com/40

react-query를 사용했을때 next랑 조금 다르게 적용되는거 같더라구요!
다음 next로 작업할 때 참고해서 작업해보면 좋을거 같아서 미리 커멘트 달아요!!

2024-03-09 02:35 UTC, mingnana commented on src/components/features/contents/detail/detail.tsx
> +    if (!contentsData || !commentData) {
아! 저는 뭔가 로딩이나 스켈레톤 컴포넌트를 넣게되면.. 사용자가 데이터가 있는줄알고 계속 기다리는 상황이 오지않을까 해서 아예 없다는 컴포넌트를 만들어야 하나 했었어요!
다른 api 작업이 꽤 남아서 우선 나머지 작업 진행하고, 이부분은 나중에 로딩컴포넌트로 대체하는 작업 진행해도 될까요!

2024-03-12 03:47 UTC, bbung95 reviewed
고생하셨습니다! 머지하시죠!

2024-03-12 03:47 UTC, bbung95 commented on src/api/contents.ts
> +export const CONTENT_API = {
민아님! 혹시 이 부분 객체로 분리하신 이유가 있으신가요!!

위에 Promise<IcontentResponse> 타입 부분도 기존의 fetchData.get<IcontentResponse>로 작성하셔도 타입 추론이 가능할거 같아요!

그리고 throw new Error 부분이 catch 밖에 있는거 같은데 혹시 어떤 동작을 기대하시는지 알 수 있을까요!!??

2024-03-12 03:47 UTC, bbung95 commented on src/components/features/contents/detail/detail.tsx
> +    if (!contentsData || !commentData) {
이건 말씀하신거처럼 기획적인 부분이라 생각이 들어서 이번에는 편하신대로 작업해주셔도 될거같아요! 해보고 싶은 방향으로 진행해주셔도 됩니다!

2024-03-12 03:48 UTC, bbung95 approved these changes

2024-03-12 03:50 UTC, bbung95 commented on src/api/comment.ts
> +        staleTime: 60000,
staleTime 좋습니다!! 
60000도 좋은데 저는 한눈에 시간이 얼마인지 알아보기 어려운거 같아요ㅠㅠ
1000 * 60 * 5 (5분) 과 같이 나눠봐도 좋을거 같아요!

2024-03-12 07:37 UTC, mingnana commented on src/api/contents.ts
> +export const CONTENT_API = {
글과 관련한 api를 전부 content_api 에 넣으려고 했습니다~ 글작성하는 api도 메서드로 만들어서 추가하려고 했었어요!

2024-03-12 07:48 UTC, mingnana commented on src/api/contents.ts
> +export const CONTENT_API = {
throw 부분은 잘못넣은것같ㄴ요! 수정했습니다

2024-03-13 11:36 UTC, merged