Feat/dev design system : typography desgin System 일부 적용 및 vitest type 에러 수정
ate-eight/sell-your-unhappiness-front pull request #7
Opened 2024-01-31 06:34 UTC by heywon0909

## 📖 관련 문서

노션 : https://www.notion.so/design-system-286ce4d0817a4104b6e2e0768e73c7e2?pvs=4

## ✍🏻 변경사항:

1. theme.ts 에 typhograpy object 생성
2. storybook 폴더에 preview-body.html 생성
3. fonts 폴더에 pretendard web font 다운
4. vite.config.ts 의 vitest test property 를 vitest.config.ts 파일로 이동 

## 🔍 확인할 목록

storybook 화면 내용 확인해보기

2024-01-31 06:52 UTC, mingnana reviewed
와 고생하셨습니다!👍🏻👍🏻 머지하시죠!!

2024-01-31 06:55 UTC, mingnana requested changes
와 고생하셨습니다!👍🏻👍🏻 머지하시죠!!

2024-01-31 06:56 UTC, mingnana approved these changes

2024-01-31 15:25 UTC, bbung95 commented on .storybook/blocks/StoryName/StoryName.tsx
StoryName은 어떤 역할을 하는건가요!!?

2024-01-31 15:25 UTC, bbung95 approved these changes
오아! 대박이네요...! 고생하셨습니다!!

2024-02-01 00:48 UTC, heywon0909 commented on .storybook/blocks/StoryName/StoryName.tsx
mdx 파일처럼 storyblock을 만들 수 있데요..! 앗 근데 이거 안사용했는데 넣어놨네요...ㅠㅠ 빼겠습니다!

2024-02-01 00:49 UTC, merged

2024-02-01 09:59 UTC, bbung95 commented on .storybook/blocks/StoryName/StoryName.tsx
오호! 다음에 한번 해봐야겠네요! 감사합니다!!